name: EventManager
version: '${project.version}'
main: me.padej.eventmanager.main.EventManager
api-version: '1.20'

commands:
  event_manager:
    description: Наслаждайтесь проведением ивентов.
    usage: /event_manager
    permission: event_manager.event
    aliases:
      - em